keys:
  - &users:
    - &thomas 7A53D4C6B481F7711588D34FDE749C31D060A160
  - &hosts:
    - &throwaway age160n4r08zhxqzy4a02p2tu3pxrcks2y5g20qw2c6x44svfmddk5ms092wlt

creation_rules:
  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
    - age:
      - *throwaway
      pgp:
      - *thomas

